version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - db
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
  db:
    container_name: db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
