version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - 3000:3000
    healthcheck:
      test: curl -fs http://localhost:3000/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
